---
heat_template_version: 2016-04-08

description: A Group of Load Balanced Servers

parameters:
  app_image:
    type: string
    label: Application Machine Image
    description: Glance Image for the application server
    default: None
  app_flavor:
    type: string
    label: Application Instance Flavor
    description: Nova Flavor for the application server
    default: m1.medium
  app_port:
    type: number
    label: Application Listening Port
    description: Port used by the application servers
    default: 80
  external_network:
    type: string
    label: Public Network
    description: Expose the LBaaS loadbalancer on this network
    default: None
    constraints:
      - custom_constraint: neutron.network
  lb_port:
    type: number
    label: LBaaS Listener Port
    description: Port used by the LBaaS listener
    default: 443
  lb_type:
    type: string
    label: LBaaS Protocol Type
    description: "LBaaS type: TCP, HTTP"
    default: TCP
  lb_method:
    type: string
    label: LBaaS Pool LB Method
    description: "LBaaS LB method: LEAST_CONNECTIONS, ROUND_ROBIN, SOURCE_IP"
    default: LEAST_CONNECTIONS
  lb_monitor:
    type: string
    label: LBaaS Health Monitor
    description: "LBAaS Health Monitor type: PING, TCP, HTTP"
    default: PING
  lb_pool_member_count:
    type: number
    label: Application Instances
    description: Number of application instances to load balance
    default: 2

resources:

  # Nonce for unique naming
  name_nonce:
    type: OS::Heat::RandomString
    properties:
      length: 8
      sequence: lowercase

  # Single tier networking
  app_network:
    type: OS::Neutron::Net
    properties:
      name:
        list_join:
          - '-'
          - ['app-network',{get_resource: name_nonce}]

  app_subnet:
    type: OS::Neutron::Subnet
    properties:
      name:
        list_join:
          - '-'
          - ['app-subnet',{get_resource: name_nonce}]
      network_id: {get_resource: app_network}
      cidr: '192.168.155.0/24'
      gateway_ip: '192.168.155.1'
      allocation_pools:
        - start: '192.168.155.20'
          end: '192.168.155.200'

  lb_network:
    type: OS::Neutron::Net
    properties:
      name:
        list_join:
          - '-'
          - ['lb-network',{get_resource: name_nonce}]

  lb_subnet:
    type: OS::Neutron::Subnet
    properties:
      name:
        list_join:
          - '-'
          - ['lb-subnet',{get_resource: name_nonce}]
      network_id: {get_resource: lb_network}
      cidr: '192.168.156.0/24'
      gateway_ip: '192.168.156.1'
      allocation_pools:
        - start: '192.168.156.20'
          end: '192.168.156.200'

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: {get_param: external_network}

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: {get_resource: router}
      subnet_id: {get_resource: app_subnet}

  router_interface_2:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: {get_resource: router}
      subnet_id: {get_resource: lb_subnet}

  # Port level security - E/W firewalling
  app_tcp_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: security group rules for TCP listeners on the application server
      name:
        list_join:
          - '-'
          - ['sg-tcp',{get_resource: name_nonce}]
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: {get_param: app_port}
          port_range_max: {get_param: app_port}
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22

  app_icmp_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: security group rules for ICMP to the application server
      name:
        list_join:
          - '-'
          - ['sg-icmp',{get_resource: name_nonce}]
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

  # Application services
  servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: lb_pool_member_count}
      resource_def:
        type: LBaaS::AppServerInstance
        properties:
          app_image: {get_param: app_image}
          app_flavor: {get_param: app_flavor}
          use_config_drive: true
          app_network: {get_resource: app_network}
          app_subnet: {get_resource: app_subnet}
          app_security_groups:
            str_replace:
              template: tcp_security,icmp_security
              params:
                tcp_security: {get_resource: app_tcp_security_group}
                icmp_security: {get_resource: app_icmp_security_group}
          app_server_index: "%index%"
          pool_id: {get_resource: pool}
          lbaas_port: {get_param: app_port}

  # Application delivery functions
  monitor:
    type: OS::Neutron::LBaaS::HealthMonitor
    properties:
      delay: 3
      type: {get_param: lb_monitor}
      timeout: 3
      max_retries: 3
      pool: {get_resource: pool}

  pool:
    type: OS::Neutron::LBaaS::Pool
    properties:
      lb_algorithm: {get_param: lb_method}
      protocol: {get_param: lb_type}
      listener: {get_resource: listener}

  listener:
    type: OS::Neutron::LBaaS::Listener
    properties:
      loadbalancer: {get_resource: loadbalancer}
      protocol: {get_param: lb_type}
      protocol_port: {get_param: lb_port}

  loadbalancer:
    type: OS::Neutron::LBaaS::LoadBalancer
    properties:
      vip_subnet: {get_resource: lb_subnet}

  floatingip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: external_network}
      port_id: {get_attr: [loadbalancer, vip_port_id]}

  esd:
    type: OS::Neutron::LBaaS::L7Policy
    properties:
      name: dmzmobile
      description: add corporate Internet mobile application ADC policies
      listener: {get_resource: listener}
      action: REJECT

outputs:
  lburl:
    value:
      str_replace:
        template: https://IP_ADDRESS:PORT
        params:
          IP_ADDRESS: {get_attr: [floatingip, floating_ip_address]}
          PORT: {get_param: lb_port}
    description: >
      This URL is the "external" URL that can be used to access the
      load balancer.
